services:
  job-recommendation-agent:
    container_name: job-recommendation-agent
    build: .
    
    volumes:
      - ./resumes:/app/resumes

    env_file:
      - .env
    
    ports:
      - "127.0.0.1:8080:8080"

    restart: unless-stopped